### ISSUE TITLE
1617 SQLSTATE [IM004, 0]: [unixODBC][Driver Manager]Driver's SQLAllocHandle on SQL_HANDLE_HENV failed

### ISSUE THREAD

**Issue by bizmate** [Microsoft/msphpsql#400]
Hi I am running the new drivers under php:fpm on docker with the following Dockerfile

```
FROM php:fpm
MAINTAINER Diego Gullo <diego_gullo@bizmate.biz>

# Add Microsoft repo for Microsoft ODBC Driver 13 for Linux
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/8/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update

# Install Dependencies
RUN ACCEPT_EULA=Y apt-get install -y \
    unixodbc \
    unixodbc-dev \
    libgss3 \
    odbcinst \
    msodbcsql \
    locales \
    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen

# Install pdo_sqlsrv and sqlsrv from PECL. Replace pdo_sqlsrv-4.1.8preview with preferred version.
RUN pecl install pdo_sqlsrv-4.1.9preview sqlsrv-4.1.9preview \
    && docker-php-ext-enable pdo_sqlsrv sqlsrv

RUN apt-get install -y libpq-dev libcurl4-gnutls-dev \
	&& docker-php-ext-install curl pdo pdo_pgsql
```

When running a query I get the error

1617 SQLSTATE [IM004, 0]: [unixODBC][Driver Manager]Driver's SQLAllocHandle on SQL_HANDLE_HENV failed

I am using the preview version 9 because the stable packages wont work and give this error when running  a build

```
ERROR: `make' failed
error: /usr/local/lib/php/extensions/no-debug-non-zts-20160303/pdo_sqlsrv does not exist
```
A full log provided in the file
[pecl_install_sqlsrv_Fails.txt](https://github.com/Microsoft/msphpsql/files/1011436/pecl_install_sqlsrv_Fails.txt)

Any suggestions on how to fix the problem is appreciated

**Comment by david-puglielli** [comment]
@bizmate I'm having trouble reproducing this error. Could you provide the sequence of shell commands you are using and the php script?

**Comment by bizmate** [comment]
This is a silex app in php and I am just running a select version on the db (the error happens with real apps and complex queries too)
I give the db details through env variables

```
export DB_DATABASE=master
export DB_PASSWORD=XXXXXXXX
export DB_HOSTNAME=192.168.0.10
export DB_USERNAME=SA
```

once the script below is running you can call http://localhost:8080/mssql

```
require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;

$app = new Silex\Application();

$app->error(function (\Exception $e, Request $request, $code) {
    switch ($code) {
        case 404:
            $message = 'The requested page could not be found.';
            break;
        default:
            $message = 'ERROR : ' . get_class($e) . ' code: ' . $e->getCode() . ' msg: ' . $e->getMessage();
    }

    return new Response($message);
});

$app->get('/hello/{name}', function ($name) use ($app) {
    return 'Hello '.$app->escape($name);
});

$app->get('/info', function () use ($app) {
    return phpinfo();
    //return 'Hello '. $app->escape( json_encode(ini_get_all()) );
});

$app->get('/dbparam', function () use ($app) {
    return '<br>DB_DATABASE: ' . getenv('DB_DATABASE') .
    '<br>DB_USERNAME: ' . getenv('DB_USERNAME') .
    '<br>DB_PASSWORD: ' . getenv('DB_PASSWORD') .
    '<br>DB_HOSTNAME: ' . getenv('DB_HOSTNAME');
});

$app->get('/mssql', function () use ($app) {

    $serverName = getenv('DB_HOSTNAME');
    $connectionOptions = array(
        "Database" => getenv('DB_DATABASE'),
        "Uid" => getenv('DB_USERNAME'),
        "PWD" => getenv('DB_PASSWORD')
    );
    //Establishes the connection
    $conn = sqlsrv_connect($serverName, $connectionOptions);

    if($conn) {
        echo "Connection established.\n";
    } else {
        echo "Connection could not be established.\n";
        die( print_r( sqlsrv_errors(), true));
    }

    //Select Query
    $tsql= "SELECT @@Version as SQL_VERSION";
    //Executes the query
    $getResults= sqlsrv_query($conn, $tsql);
    //Error handling

    $output = "<h1> Results : </h1>";

    if ($getResults == FALSE){
        $errors = sqlsrv_errors();
        /* Display errors. */
        $output .= "<br/><br/>Error information: " ;

        foreach ( $errors as $error )
        {
            $output .= "<br/> SQLSTATE: ".$error['SQLSTATE'];
            $output .= "<br/>Code: ".$error['code'];
            $output .= "<br/>Message: ".$error['message'];
        }
        throw new Exception($output);
    }

    while ($row = sqlsrv_fetch_array($getResults, SQLSRV_FETCH_ASSOC)) {
        $output .= "<br/> Sql version : " . $row['SQL_VERSION'];
    }
    sqlsrv_free_stmt($getResults);

    return $output;
});

$app->run();
```

You can use this docker-compose.y

[nginx.conf.txt](https://github.com/Microsoft/msphpsql/files/1012464/nginx.conf.txt)

ml file

```
version: '2'

services:
  data:
   image: busybox
   user: $UID
   volumes:
     - ./:/var/www/html/:z

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/php7/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - data
    depends_on:
      - php7

  php7:
    build: docker/php7
    user: $UID
    ports:
      - "9000"
    volumes:
      - ./docker/config/php7.ini:/usr/local/etc/php/php.ini
      - ./docker/config/odbcinst.ini:/etc/odbcinst.ini
      - ./docker/config/freetds.conf:/etc/freetds/freetds.conf

    volumes_from:
     - data
    environment:
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - DB_HOSTNAME
    security_opt:
      - seccomp:unconfined
```

See the nginx, php, odbcinst and freetds files attached. 
[odbcinst.ini.txt](https://github.com/Microsoft/msphpsql/files/1012479/odbcinst.ini.txt)
[php7.ini.txt](https://github.com/Microsoft/msphpsql/files/1012480/php7.ini.txt)
[freetds.conf.txt](https://github.com/Microsoft/msphpsql/files/1012477/freetds.conf.txt)
[nginx.conf.txt](https://github.com/Microsoft/msphpsql/files/1012478/nginx.conf.txt)

When you call the page you will see the error

```
Connection could not be established. Array ( [0] => Array ( [0] => IM004 [SQLSTATE] => IM004 [1] => 0 [code] => 0 [2] => [unixODBC][Driver Manager]Driver's SQLAllocHandle on SQL_HANDLE_HENV failed [message] => [unixODBC][Driver Manager]Driver's SQLAllocHandle on SQL_HANDLE_HENV failed ) )
```
